/**
 * ADR page registry — GENERATED by scripts/gen-adr-registry.mjs from
 * docs/adr/ADR-*.md.  DO NOT EDIT BY HAND; re-run `make gen-adr` instead.
 *
 * ADRs are MADR-format (no `kind` facet), so each record carries number,
 * title (the MADR H1), status, and date.  Single source of truth shared by:
 *   - src/pages/modelling/adr/index.astro  (listing)
 *   - src/pages/modelling/adr/[id].astro   (detail-page meta pill + breadcrumb)
 *   - src/lib/site.ts                       (left-nav group)
 *
 * Each ADR's body renders through the Astro `adr` content collection
 * (render(entry) → <Content/> in [id].astro) — the same pipeline as ODRs.
 */

/**
 * @typedef {Object} AdrEntry
 * @property {string} id      - Kebab-case page id, e.g. 'adr-0001'
 * @property {string} number  - Zero-padded number, e.g. '0001'
 * @property {string} title   - MADR H1 title
 * @property {string} status  - 'accepted' | 'proposed' | 'superseded' | 'rejected' | ''
 * @property {string} date    - ISO date string from frontmatter, or ''
 */

/** All 54 ADRs in the corpus. Every ADR gets a live page. */
export const ADR_REGISTRY = [
  { id: "adr-0001", number: "0001", title: "Selective adoption of DCAM v3 and DAMA-DMBOK2 elements", status: "accepted", date: "2026-05-18" },
  { id: "adr-0002", number: "0002", title: "Folder hierarchy and slug taxonomy", status: "accepted", date: "2026-05-18" },
  { id: "adr-0003", number: "0003", title: "Refactor to idiomatic Astro architecture", status: "accepted", date: "2026-05-18" },
  { id: "adr-0004", number: "0004", title: "Accreditation Directory spec", status: "accepted", date: "2026-05-18" },
  { id: "adr-0005", number: "0005", title: "Deferred work register from the 2026-05-18 implementation push", status: "accepted", date: "2026-05-18" },
  { id: "adr-0006", number: "0006", title: "Ontology namespace at w3id.org/opda/ via W3C PICG redirect", status: "accepted", date: "2026-05-27" },
  { id: "adr-0007", number: "0007", title: "Ontology generator — deterministic emission specification", status: "accepted", date: "2026-05-27" },
  { id: "adr-0008", number: "0008", title: "Ontology generator — implementation infrastructure", status: "accepted", date: "2026-05-27" },
  { id: "adr-0009", number: "0009", title: "Foundation TTL emission", status: "accepted", date: "2026-05-27" },
  { id: "adr-0010", number: "0010", title: "SKOS vocabulary emission", status: "accepted", date: "2026-05-27" },
  { id: "adr-0011", number: "0011", title: "Module TBox emission", status: "accepted", date: "2026-05-27" },
  { id: "adr-0012", number: "0012", title: "SHACL shapes + DPV annotation emission", status: "accepted", date: "2026-05-27" },
  { id: "adr-0013", number: "0013", title: "Overlay profile emission", status: "accepted", date: "2026-05-27" },
  { id: "adr-0014", number: "0014", title: "BASPI5 round-trip MVP harness + diagnostic exemplar regression", status: "accepted", date: "2026-05-27" },
  { id: "adr-0015", number: "0015", title: "Integrate 4-tier ontology manual into the Astro site", status: "accepted", date: "2026-05-28" },
  { id: "adr-0016", number: "0016", title: "Manual content-collection wiring + site navigation", status: "accepted", date: "2026-05-28" },
  { id: "adr-0017", number: "0017", title: "Manual component library (12 reusable components + accent tokens)", status: "accepted", date: "2026-05-28" },
  { id: "adr-0018", number: "0018", title: "Manual build-time remark + rehype plugins", status: "accepted", date: "2026-05-28" },
  { id: "adr-0019", number: "0019", title: "Modelling-section / manual handshake", status: "accepted", date: "2026-05-28" },
  { id: "adr-0020", number: "0020", title: "Generator emission of manual content-collection frontmatter", status: "accepted", date: "2026-05-28" },
  { id: "adr-0021", number: "0021", title: "Generate manual entity pages from the ontology via Fuseki + a GRLC SPARQL API at build time", status: "accepted", date: "2026-05-28" },
  { id: "adr-0022", number: "0022", title: "Make manual diagram elements clickable (navigate to entity pages)", status: "accepted", date: "2026-05-28" },
  { id: "adr-0023", number: "0023", title: "Build-time ODR pages: convert markdown to enriched HTML once, freeze, and commit", status: "superseded", date: "2026-05-29" },
  { id: "adr-0024", number: "0024", title: "ODR enrichment lives in the markdown; HTML is generated from it every build", status: "accepted", date: "2026-05-29" },
  { id: "adr-0025", number: "0025", title: "The CSS architecture: Claude Design is authoritative; Tailwind is a scoped guest", status: "accepted", date: "2026-05-29" },
  { id: "adr-0026", number: "0026", title: "Bounded-Context Scheme Emission", status: "accepted", date: "2026-05-30" },
  { id: "adr-0027", number: "0027", title: "Council-Session Indexing in AgentDB", status: "accepted", date: "2026-05-30" },
  { id: "adr-0028", number: "0028", title: "Descriptive-Layer Walk Emission and Generated Home-Pass", status: "accepted", date: "2026-05-30" },
  { id: "adr-0029", number: "0029", title: "Overlay-Profile Emitter Generalisation and Full Rollout", status: "accepted", date: "2026-05-30" },
  { id: "adr-0030", number: "0030", title: "Category-Based Descriptive Emission Pipeline & Import Gates (G1–G3)", status: "accepted", date: "2026-05-30" },
  { id: "adr-0031", number: "0031", title: "Category-G Curated Walk — Execution Plan and G11 Reconciliation", status: "accepted", date: "2026-05-30" },
  { id: "adr-0032", number: "0032", title: "Curated Category-G Walk — Emission, Coverage Gate, and ODR-0024 Remediation", status: "accepted", date: "2026-05-31" },
  { id: "adr-0033", number: "0033", title: "Room-Dimension Value-Structure Emission", status: "accepted", date: "2026-05-31" },
  { id: "adr-0034", number: "0034", title: "Gated gUFO `rdf:type` Property-Typing Pass", status: "accepted", date: "2026-05-31" },
  { id: "adr-0035", number: "0035", title: "Load-Time OWL-RL-Safe Inference Materialisation in Jena/Fuseki", status: "accepted", date: "2026-06-01" },
  { id: "adr-0036", number: "0036", title: "SHACL 1.2 Validation via Apache Jena", status: "accepted", date: "2026-06-01" },
  { id: "adr-0037", number: "0037", title: "Apache Jena as opda's Sole RDF/SHACL/SPARQL 1.2 Toolchain", status: "accepted", date: "2026-06-01" },
  { id: "adr-0038", number: "0038", title: "Hosting, auth, and comments architecture (AWS)", status: "accepted", date: "2026-06-06" },
  { id: "adr-0039", number: "0039", title: "Linked-data model as the foundation and direction of PDTF standards development", status: "accepted", date: "2026-06-03" },
  { id: "adr-0040", number: "0040", title: "AWS hosting CI/CD pipeline", status: "accepted", date: "2026-06-06" },
  { id: "adr-0041", number: "0041", title: "Ontology Reference Document — Generation Model and Section Structure", status: "accepted", date: "2026-06-14" },
  { id: "adr-0042", number: "0042", title: "Rename the `/manual` Section to `/model`", status: "accepted", date: "2026-06-14" },
  { id: "adr-0043", number: "0043", title: "Ontology graph-diagram tooling — interactive engine + authored + static-gated composition", status: "accepted", date: "2026-06-14" },
  { id: "adr-0044", number: "0044", title: "Ontology as web pages — dereferenceable per-entity detail pages, SPARQL-driven SSG", status: "accepted", date: "2026-06-14" },
  { id: "adr-0045", number: "0045", title: "`ufoCategory` quarantine restoration, gUFO-alignment scheme, and the sixth three-graph gate", status: "accepted", date: "2026-06-15" },
  { id: "adr-0046", number: "0046", title: "OntoClean meta-property markup — conditional, gated on the canonical-check CI meta-shape", status: "accepted", date: "2026-06-15" },
  { id: "adr-0047", number: "0047", title: "Ontology graph-engine in-situ bake-off — every scored finalist as a switchable tab", status: "accepted", date: "2026-06-16" },
  { id: "adr-0048", number: "0048", title: "Relationship-emission walk + object-property coverage gate", status: "proposed", date: "2026-06-17" },
  { id: "adr-0049", number: "0049", title: "OWL axioms as documentary AI-signal — domain/range and the R2-excluded set", status: "proposed", date: "2026-06-17" },
  { id: "adr-0050", number: "0050", title: "Single canonical UFO typing axis", status: "proposed", date: "2026-06-17" },
  { id: "adr-0051", number: "0051", title: "Site content realignment: DVSTF/SPDTF terminology, UK-initiative chart, standards alignment, and the MHCLG roadmap", status: "proposed", date: "2026-06-25" },
  { id: "adr-0052", number: "0052", title: "Stakeholder-review remediation: member parity, propdata.org.uk provenance, Moverly, and accreditation-gap corrections", status: "proposed", date: "2026-06-25" },
  { id: "adr-0053", number: "0053", title: "Cache the Apache Jena Fuseki dist in the AWS deploy", status: "accepted", date: "2026-06-25" },
  { id: "adr-0054", number: "0054", title: "Publish the source/ archive to a public S3 bucket served via CloudFront", status: "proposed", date: "2026-06-25" },
];
