/**
 * Typed accessor over the committed ADR-0044 ontology model.
 *
 * `src/data/ontology-model.json` is generated by `scripts/ontology-model.mjs`
 * from the live Fuseki dataset (operator decision b) and committed for the
 * doc-drift gate + ADR-0043 graph sharing. It is read here AT BUILD TIME by the
 * `/pdtf` dereference route and the `/ontology` typed indexes — no runtime query.
 *
 * Each resource is keyed by its id = the path after `https://opda.org.uk/pdtf/`
 * (e.g. `Property`, `annualCostOfPermit`, `shape/PropertyIdentityKeyShape`,
 * `scheme/TenureScheme`). That id is also the URL slug under `/pdtf/`.
 */
import modelJson from '@/data/ontology-model.json';

export interface Ref {
  id: string;
  localName: string;
  /** 'class' | 'scheme' | 'datatype' | 'external' — only present on edge targets. */
  kind?: string;
}

export interface OutgoingEdge {
  predicate: string;
  predicateLabel: string;
  predicateLocal: string;
  targets: Ref[];
  inverse: string | null;
  description: string;
}

export interface IncomingEdge {
  predicate: string;
  predicateLabel: string;
  predicateLocal: string;
  sources: Ref[];
  inverse: string | null;
  description: string;
}

export interface Attribute {
  localName: string;
  id: string;
  label: string;
  type: string | null;
  description: string;
}

export interface ShapeRef {
  id: string;
  localName: string;
}

export interface ClassEntry {
  uri: string;
  id: string;
  localName: string;
  label: string;
  comment: string;
  scopeNote: string;
  module: string | null;
  context: string | null;
  attributes: Attribute[];
  outgoing: OutgoingEdge[];
  incoming: IncomingEdge[];
  shapes: ShapeRef[];
  usesSchemes: Ref[];
  dctSource: string[];
}

export interface Constraint {
  shape: string;
  path: string;
  pathLocal: string;
  datatype: string | null;
  class: string | null;
  minCount: string | null;
  maxCount: string | null;
  severity: string | null;
  message: string | null;
}

export interface PropertyEntry {
  uri: string;
  id: string;
  localName: string;
  label: string;
  comment: string;
  kind: 'object' | 'datatype';
  module: string | null;
  subjects: Ref[];
  objects: Ref[];
  inverse: { id: string; localName: string } | null;
  constraints: Constraint[];
  dctSource: string[];
}

export interface OntologyModel {
  namespace: string;
  counts: Record<string, number>;
  classes: Record<string, ClassEntry>;
  objectProperties: Record<string, PropertyEntry>;
  datatypeProperties: Record<string, PropertyEntry>;
  // Phase 3 will give these proper interfaces; untyped for now.
  shapes: Record<string, Record<string, unknown>>;
  concepts: Record<string, Record<string, unknown>>;
  schemes: Record<string, Record<string, unknown>>;
  contexts: Record<string, Record<string, unknown>>;
}

export const model = modelJson as unknown as OntologyModel;

/** The ontology base IRI — `https://opda.org.uk/pdtf/`. */
export const NS = model.namespace;

/** The full dereferenceable IRI for a model id. */
export const iri = (id: string): string => NS + id;

/** The on-site canonical URL for a model id (ADR-0044 §Decisions a). */
export const pdtfUrl = (id: string): string => `/pdtf/${id}`;

/** A term (class or property) tagged with its kind, for the /pdtf dispatcher. */
export type AnyTerm =
  | ({ entryKind: 'class' } & ClassEntry)
  | ({ entryKind: 'property' } & PropertyEntry);

/**
 * Every term the `/pdtf` route serves in Phase 2: classes + object properties +
 * datatype properties. Phase 3 extends the route with shapes/concepts/schemes.
 */
export function allTerms(): AnyTerm[] {
  return [
    ...Object.values(model.classes).map((c) => ({ entryKind: 'class' as const, ...c })),
    ...Object.values(model.objectProperties).map((p) => ({ entryKind: 'property' as const, ...p })),
    ...Object.values(model.datatypeProperties).map((p) => ({ entryKind: 'property' as const, ...p })),
  ];
}
