/**
 * Typed accessor over the committed ADR-0044 ontology model.
 *
 * `src/data/ontology-model.json` is generated by `scripts/ontology-model.mjs`
 * from the live Fuseki dataset (operator decision b) and committed for the
 * doc-drift gate + ADR-0043 graph sharing. It is read here AT BUILD TIME by the
 * `/pdtf` dereference route and the `/ontology` typed indexes — no runtime query.
 *
 * Each resource is keyed by its id = the path after `https://opda.org.uk/pdtf/`
 * (e.g. `Property`, `annualCostOfPermit`, `shape/PropertyIdentityKeyShape`,
 * `scheme/TenureScheme`). That id is also the URL slug under `/pdtf/`.
 */
import modelJson from '@/data/ontology-model.json';

export interface Ref {
  id: string;
  localName: string;
  /** 'class' | 'scheme' | 'datatype' | 'external' — only present on edge targets. */
  kind?: string;
}

export interface OutgoingEdge {
  predicate: string;
  predicateLabel: string;
  predicateLocal: string;
  targets: Ref[];
  inverse: string | null;
  description: string;
}

export interface IncomingEdge {
  predicate: string;
  predicateLabel: string;
  predicateLocal: string;
  sources: Ref[];
  inverse: string | null;
  description: string;
}

export interface Attribute {
  localName: string;
  id: string;
  label: string;
  type: string | null;
  description: string;
}

export interface ShapeRef {
  id: string;
  localName: string;
}

export interface ClassEntry {
  uri: string;
  id: string;
  localName: string;
  label: string;
  comment: string;
  scopeNote: string;
  ufoCategory: string;
  module: string | null;
  context: string | null;
  attributes: Attribute[];
  outgoing: OutgoingEdge[];
  incoming: IncomingEdge[];
  shapes: ShapeRef[];
  usesSchemes: Ref[];
  dctSource: string[];
}

export interface Constraint {
  /** Set only when listed under a property (shapesByPath); absent on a shape's own constraints. */
  shape?: string;
  path: string;
  pathLocal: string;
  datatype: string | null;
  class: string | null;
  minCount: string | null;
  maxCount: string | null;
  severity: string | null;
  message: string | null;
}

export interface PropertyEntry {
  uri: string;
  id: string;
  localName: string;
  label: string;
  comment: string;
  kind: 'object' | 'datatype';
  module: string | null;
  subjects: Ref[];
  objects: Ref[];
  inverse: { id: string; localName: string } | null;
  constraints: Constraint[];
  dctSource: string[];
}

export interface OntologyModel {
  namespace: string;
  counts: Record<string, number>;
  classes: Record<string, ClassEntry>;
  objectProperties: Record<string, PropertyEntry>;
  datatypeProperties: Record<string, PropertyEntry>;
  shapes: Record<string, ShapeEntry>;
  concepts: Record<string, ConceptEntry>;
  schemes: Record<string, SchemeEntry>;
  contexts: Record<string, ContextEntry>;
}

export interface ShapeEntry {
  uri: string;
  id: string;
  localName: string;
  module: string | null;
  target: { id: string; localName: string } | null;
  targetSubjectsOf: string | null;
  constraints: Constraint[];
}

export interface ConceptEntry {
  uri: string;
  id: string;
  localName: string;
  prefLabel: string;
  definition: string;
  module: string | null;
  schemes: Ref[];
  broader: Ref[];
  narrower: Ref[];
  dctSource: string[];
}

export interface SchemeEntry {
  uri: string;
  id: string;
  localName: string;
  prefLabel: string;
  definition: string;
  ufoCategory: string;
  module: string | null;
  topConcepts: Ref[];
  concepts: Ref[];
}

export interface ContextEntry {
  id: string;
  localName: string;
  classes: Ref[];
  objectProperties: Ref[];
  datatypeProperties: Ref[];
  shapes: Ref[];
  schemes: Ref[];
}

export const model = modelJson as unknown as OntologyModel;

/** The ontology base IRI — `https://opda.org.uk/pdtf/`. */
export const NS = model.namespace;

/** The full dereferenceable IRI for a model id. */
export const iri = (id: string): string => NS + id;

/** The on-site canonical URL for a model id (ADR-0044 §Decisions a). */
export const pdtfUrl = (id: string): string => `/pdtf/${id}`;

/** A term (class or property) tagged with its kind, for the /pdtf dispatcher. */
export type AnyTerm =
  | ({ entryKind: 'class' } & ClassEntry)
  | ({ entryKind: 'property' } & PropertyEntry);

/**
 * Every term the `/pdtf` route serves in Phase 2: classes + object properties +
 * datatype properties. Phase 3 extends the route with shapes/concepts/schemes.
 */
export function allTerms(): AnyTerm[] {
  return [
    ...Object.values(model.classes).map((c) => ({ entryKind: 'class' as const, ...c })),
    ...Object.values(model.objectProperties).map((p) => ({ entryKind: 'property' as const, ...p })),
    ...Object.values(model.datatypeProperties).map((p) => ({ entryKind: 'property' as const, ...p })),
  ];
}

/** The id (path after the opda base) of a full opda IRI; the IRI unchanged otherwise. */
export const idOf = (uri: string): string => (uri && uri.startsWith(NS) ? uri.slice(NS.length) : uri);
/** Whether a URI is a dereferenceable opda resource (so it can link to /pdtf). */
export const isOpda = (uri: string): boolean => !!uri && uri.startsWith(NS);

/** The 7 canonical bounded-context module ids (ADR-0044 Phase-1 refinement). */
export const CONTEXTS: string[] = Object.keys(model.contexts);
export const isContext = (m: string | null | undefined): boolean => !!m && CONTEXTS.includes(m);
/** The /ontology/context page URL for a module, or null if it isn't one of the 7. */
export const contextUrl = (m: string | null | undefined): string | null =>
  (isContext(m) ? `/ontology/context/${m}` : null);

/**
 * Every resource the /pdtf route serves: terms + shapes + concepts + schemes.
 * (Bounded contexts are NOT here — they are graph-derived module groupings, not
 * minted opda: term IRIs, so they live at /ontology/context/{id}.)
 */
export type AnyResource =
  | ({ entryKind: 'class' } & ClassEntry)
  | ({ entryKind: 'property' } & PropertyEntry)
  | ({ entryKind: 'shape' } & ShapeEntry)
  | ({ entryKind: 'concept' } & ConceptEntry)
  | ({ entryKind: 'scheme' } & SchemeEntry);

export function allResources(): AnyResource[] {
  return [
    ...Object.values(model.classes).map((c) => ({ entryKind: 'class' as const, ...c })),
    ...Object.values(model.objectProperties).map((p) => ({ entryKind: 'property' as const, ...p })),
    ...Object.values(model.datatypeProperties).map((p) => ({ entryKind: 'property' as const, ...p })),
    ...Object.values(model.shapes).map((s) => ({ entryKind: 'shape' as const, ...s })),
    ...Object.values(model.concepts).map((c) => ({ entryKind: 'concept' as const, ...c })),
    ...Object.values(model.schemes).map((s) => ({ entryKind: 'scheme' as const, ...s })),
  ];
}

/** Slug for a UFO category label (e.g. "Substance Kind" → "substance-kind"). */
export const ufoSlug = (cat: string): string =>
  cat.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

/** The UFO meta-categories (ADR-0044 Phase 5c) → the classes bearing each. */
export function ufoCategories(): { category: string; slug: string; classes: ClassEntry[] }[] {
  const by = new Map<string, ClassEntry[]>();
  for (const c of Object.values(model.classes)) {
    if (!c.ufoCategory) continue;
    if (!by.has(c.ufoCategory)) by.set(c.ufoCategory, []);
    by.get(c.ufoCategory)!.push(c);
  }
  return [...by.entries()]
    .map(([category, classes]) => ({
      category,
      slug: ufoSlug(category),
      classes: classes.sort((a, b) => a.localName.localeCompare(b.localName)),
    }))
    .sort((a, b) => b.classes.length - a.classes.length || a.category.localeCompare(b.category));
}

// ── Turtle serialisation (ADR-0044 Phase 6 — CBD + one hop, from the model) ──
const TTL_PREFIXES = `@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .`;

const XSD = 'http://www.w3.org/2001/XMLSchema#';
/** Turtle-safe quoted literal (JSON escaping is a valid Turtle string escape). */
const ttlLit = (s: string) => JSON.stringify(String(s ?? ''));
/** Percent-encode characters illegal in an IRI path (RFC 3987) — e.g. the [] in
 *  JSON-pointer dct:source ids like harness/data-dictionary/...media[].mediaUrl. */
const ttlEnc = (id: string) =>
  id.replace(/[^A-Za-z0-9\-._~!$&'()*+,;=:@/%]/g, (ch) => encodeURIComponent(ch));
/** Full IRI ref: an external URI as-is, else an opda resource id under the base. */
const ttlRef = (id: string) => (id.includes('://') ? `<${id}>` : `<${NS}${ttlEnc(id)}>`);
const ttlRange = (o: Ref) =>
  o.kind === 'datatype'
    ? (o.id.startsWith(XSD) ? `xsd:${o.localName}` : `<${o.id}>`)
    : ttlRef(o.id);
const isNum = (v: string) => /^-?\d+$/.test(v);

/**
 * Serialise one resource (by its model id) to a Turtle CBD + one-hop document —
 * the machine alternate served at /pdtf/{id}.ttl (operator decision c). Built
 * deterministically from the committed model so it matches the HTML page.
 * Returns null if the id is not a known resource.
 */
export function resourceTurtle(id: string): string | null {
  const self = ttlRef(id);
  const po: string[] = [];
  const hop: string[] = [];

  const c = model.classes[id];
  const op = model.objectProperties[id];
  const dp = model.datatypeProperties[id];
  const sh = model.shapes[id];
  const co = model.concepts[id];
  const sc = model.schemes[id];

  if (c) {
    po.push('a owl:Class', `rdfs:label ${ttlLit(c.label)}`);
    if (c.comment) po.push(`rdfs:comment ${ttlLit(c.comment)}`);
    if (c.scopeNote) po.push(`skos:scopeNote ${ttlLit(c.scopeNote)}`);
    for (const s of c.dctSource) po.push(`dct:source ${ttlRef(s)}`);
    for (const a of c.attributes) hop.push(`${ttlRef(a.id)} rdfs:label ${ttlLit(a.label)} .`);
    for (const e of c.outgoing) hop.push(`${ttlRef(e.predicate)} rdfs:label ${ttlLit(e.predicateLabel)} .`);
  } else if (op || dp) {
    const p = (op || dp)!;
    po.push(`a ${op ? 'owl:ObjectProperty' : 'owl:DatatypeProperty'}`, `rdfs:label ${ttlLit(p.label)}`);
    if (p.comment) po.push(`rdfs:comment ${ttlLit(p.comment)}`);
    for (const s of p.subjects) po.push(`rdfs:domain ${ttlRef(s.id)}`);
    for (const o of p.objects) po.push(`rdfs:range ${ttlRange(o)}`);
    if (p.inverse) po.push(`owl:inverseOf ${ttlRef(p.inverse.id)}`);
    for (const s of p.dctSource) po.push(`dct:source ${ttlRef(s)}`);
    for (const s of p.subjects) hop.push(`${ttlRef(s.id)} a owl:Class .`);
  } else if (sh) {
    po.push('a sh:NodeShape');
    if (sh.target) po.push(`sh:targetClass ${ttlRef(sh.target.id)}`);
    if (sh.targetSubjectsOf) po.push(`sh:targetSubjectsOf <${sh.targetSubjectsOf}>`);
    for (const k of sh.constraints) {
      const inner: string[] = [`sh:path <${k.path}>`];
      if (k.datatype) inner.push(`sh:datatype xsd:${k.datatype}`);
      if (k.class) inner.push(`sh:class <${k.class}>`);
      if (k.minCount != null && isNum(k.minCount)) inner.push(`sh:minCount ${k.minCount}`);
      if (k.maxCount != null && isNum(k.maxCount)) inner.push(`sh:maxCount ${k.maxCount}`);
      if (k.severity) inner.push(`sh:severity sh:${k.severity}`);
      if (k.message) inner.push(`sh:message ${ttlLit(k.message)}`);
      po.push(`sh:property [ ${inner.join(' ; ')} ]`);
    }
  } else if (co) {
    po.push('a skos:Concept', `skos:prefLabel ${ttlLit(co.prefLabel)}`);
    if (co.definition) po.push(`skos:definition ${ttlLit(co.definition)}`);
    for (const s of co.schemes) po.push(`skos:inScheme ${ttlRef(s.id)}`);
    for (const b of co.broader) po.push(`skos:broader ${ttlRef(b.id)}`);
    for (const s of co.dctSource) po.push(`dct:source ${ttlRef(s)}`);
  } else if (sc) {
    po.push('a skos:ConceptScheme', `skos:prefLabel ${ttlLit(sc.prefLabel)}`);
    if (sc.definition) po.push(`skos:definition ${ttlLit(sc.definition)}`);
    for (const t of sc.topConcepts) po.push(`skos:hasTopConcept ${ttlRef(t.id)}`);
  } else {
    return null;
  }

  let out = `${TTL_PREFIXES}\n\n${self} ${po.join(' ;\n    ')} .\n`;
  if (hop.length) out += `\n# one hop — immediate neighbours\n${[...new Set(hop)].join('\n')}\n`;
  return out;
}
