"""
Module classes.

Realises:
- ADR-0011 §"Per-module detail" — orchestrator dispatching `emit-module
  <name>` invocations to the right per-module builder in
  `opda_gen.emitters.modules.{name}`.
- ADR-0011 §"Module emission template" — prepends the generator-comment
  header to each emitted module file (ratifying ODR list + generator
  version + DO-NOT-HAND-EDIT warning).
- ADR-0008 §"CLI design" — `emit-module <name>` subcommand surface.
- ADR-0007 §"Deterministic emission rules" — serialisation goes through
  the canonical serialiser; second-run regeneration is byte-identical.
- ODR-0005 + ODR-0006 + ODR-0007 + ODR-0008 + ODR-0009 + ODR-0012 +
  ODR-0015 + ODR-0018 — the ratified `## Rules` corpus the dispatched
  module builders realise.
"""

from __future__ import annotations

from pathlib import Path

from opda_gen import __version__
from opda_gen.emitters.modules import MODULE_REGISTRY
from opda_gen.serialiser.canonical import to_canonical_turtle


# Sentinel-pinned constants per the G6 convention from ADR-0009.
# Advance when a future ADR materially mutates a module file's content.
# ADR-0014: owl:imports of foundation + per-module versionIRI bumped
# 0.4.0 → 1.0.0; opda-agent.ttl also gained opda:role declaration (G18).
_MODULES_LAST_MODIFIED = "2026-05-28"
_MODULES_SOURCE_COMMIT = "pinned-by-ADR-0014"


# Per-module metadata used by `_comment_header()`. Each tuple:
# (filename-stem, human-readable title, ratifying-ODR list).
MODULE_METADATA: dict[str, tuple[str, str, str]] = {
    "property": (
        "opda-property.ttl",
        "OPDA Property Module",
        "ODR-0005 + ODR-0015 + ODR-0008",
    ),
    "agent": (
        "opda-agent.ttl",
        "OPDA Agent Module",
        "ODR-0006",
    ),
    "transaction": (
        "opda-transaction.ttl",
        "OPDA Transaction Module",
        "ODR-0007",
    ),
    "claim": (
        "opda-claim.ttl",
        "OPDA Claim Module",
        "ODR-0009",
    ),
    "governance": (
        "opda-governance.ttl",
        "OPDA Governance Module",
        "ODR-0012 + ODR-0018",
    ),
    "descriptive": (
        "opda-descriptive.ttl",
        "OPDA Descriptive Attributes Module",
        "ODR-0008",
    ),
}


def _comment_header(
    *,
    filename: str,
    title: str,
    ratifying_odrs: str,
    emission_date: str,
    git_sha: str,
    extra_lines: list[str] | None = None,
) -> str:
    """Build the generator-comment block prepended to every module TTL.

    Per ADR-0011 §"Module emission template": cites generator version,
    source commit, ratifying ODR(s), and a DO-NOT-HAND-EDIT warning.
    """
    lines = [
        f"# {filename} — {title}",
        f"# Generated by opda-gen {__version__} at {emission_date}; "
        f"DO NOT HAND-EDIT.",
        "# Specification: "
        "https://opda.org.uk/pdtf/harness/adr/ADR-0007-ontology-generator-specification",
        "# Implementation: "
        "https://opda.org.uk/pdtf/harness/adr/ADR-0008-generator-implementation-infrastructure",
        "# This emission: "
        "https://opda.org.uk/pdtf/harness/adr/ADR-0011-module-tbox-emission",
        f"# Ratifying ODR(s): {ratifying_odrs}",
        f"# Generator version: opda-gen-{__version__}",
        f"# Source commit: {git_sha}",
    ]
    if extra_lines:
        for line in extra_lines:
            lines.append(f"# {line}")
    lines.append("")  # blank line before Turtle content
    return "\n".join(lines) + "\n"


def emit_module(
    name: str,
    output_dir: Path,
    *,
    emission_date: str | None = None,
    git_sha: str | None = None,
) -> dict[Path, str]:
    """Emit one module TTL into ``output_dir``.

    Returns a dict mapping written Path → Turtle content (utf-8 str) so
    callers (tests, CI, byte-identity runner) can inspect content without
    re-reading from disk.

    Raises ValueError if `name` is not a known module (one of property /
    agent / transaction / claim / governance / descriptive).
    """
    if name not in MODULE_REGISTRY:
        valid = ", ".join(sorted(MODULE_REGISTRY))
        raise ValueError(
            f"unknown module {name!r}; valid modules: {valid}"
        )
    builder = MODULE_REGISTRY[name]
    filename, title, ratifying_odrs = MODULE_METADATA[name]

    output_dir.mkdir(parents=True, exist_ok=True)
    date_str = emission_date or _MODULES_LAST_MODIFIED
    sha_str = git_sha or _MODULES_SOURCE_COMMIT

    graph = builder.build_graph()
    header = _comment_header(
        filename=filename,
        title=title,
        ratifying_odrs=ratifying_odrs,
        emission_date=date_str,
        git_sha=sha_str,
    )
    body = to_canonical_turtle(graph).decode("utf-8")
    content = header + body
    out_path = output_dir / filename
    out_path.write_text(content, encoding="utf-8", newline="")
    return {out_path: content}


def emit_all_modules(
    output_dir: Path,
    *,
    emission_date: str | None = None,
    git_sha: str | None = None,
) -> dict[Path, str]:
    """Emit all six module TTLs into ``output_dir`` in dependency order.

    Dependency order is: property → agent → transaction → claim →
    governance → descriptive. This matches the order used by the `emit`
    umbrella subcommand and the ADR-0011 §"Per-module detail" section
    ordering.
    """
    written: dict[Path, str] = {}
    for name in ("property", "agent", "transaction", "claim",
                 "governance", "descriptive"):
        written.update(emit_module(
            name, output_dir,
            emission_date=emission_date, git_sha=git_sha,
        ))
    return written
