"""
Module vocabularies.

Realises:
- ADR-0010 §"Scheme catalogue (initial first batch)" — 16 SKOS Concept
  Schemes emitted into `opda-vocabularies.ttl` (15 named schemes plus the
  Scottish `CouncilTaxBandSchemeScotland` variant called out as a separate
  scheme in the table).
- ADR-0010 §"Per-scheme metadata MUST-haves" — every scheme carries
  `skos:prefLabel @en`, `dct:title @en`, `skos:definition @en`,
  `dct:source`, `opda:ufoCategory`, `skos:scopeNote @en` (UFO + DOLCE
  backing), and `opda:hasSteward @en`.
- ADR-0010 §"Per-member MUST-haves" — every concept carries
  `skos:inScheme`, `skos:prefLabel @en`, `skos:notation`,
  `skos:definition @en`, and `dct:source`.
- ADR-0010 §"Emission structure" — file template with generator-comment
  header (`Generated by opda-gen <version>; DO NOT HAND-EDIT`); namespace
  imports for opda / opda-v / skos / dct / prov.
- ADR-0010 §"SHACL-AF rule emission (Cagle's deprecation-chain rule)" —
  the rule body is held as a documented constant string in this module
  (`_DEPRECATION_CHAIN_RULE_SPARQL`) so it is reviewable here, but the
  shape itself is NOT emitted into `opda-vocabularies.ttl` (that would
  violate ODR-0004 §3a three-graph separation). The rule materialises into
  `opda-shapes.ttl` under ADR-0012.
- ADR-0007 §"Deterministic emission rules" — output produced by the
  canonical serialiser; sentinel-pinned `dct:modified`; byte-identity CI
  green on regeneration.
- ADR-0007 §"A9 per-kind discipline output" — per-scheme UFO/DOLCE meta
  + IC + artefact realisation honoured for every scheme.
- ADR-0008 §"CLI design" — the `emit-vocabularies` subcommand invokes
  `emit_vocabularies()` here.
- ODR-0004 §3a — three-graph separation honoured: this emission is
  classes-side substrate; no `sh:*` triples.
- ODR-0004 §6a — deterministic emission; second-run regeneration is
  byte-identical.
- ODR-0004 §7a — per-scheme + per-member `dct:source` resolves to a
  ratified ODR section, a data-dictionary leaf, an external regulator, or
  an upstream W3C / standards specification.
- ODR-0011 §1a — each enum becomes a `skos:ConceptScheme` carrying its
  steward declaration.
- ODR-0011 §S14/§S15 — exactly one `skos:prefLabel @en` per concept;
  exactly one `skos:notation` per concept.
- ODR-0011 §4a — regulator-cited schemes (`CouncilTaxBandSchemeEW`,
  `CouncilTaxBandSchemeScotland`, `CurrentEnergyRatingScheme`) carry the
  regulator URL as `dct:source`.
- ODR-0011 §5a — deprecation-lifecycle predicates (Cagle SHACL-AF rule)
  are not yet active because no first-batch member is deprecated; the
  rule body is held verbatim as `_DEPRECATION_CHAIN_RULE_SPARQL` for
  forward use by ADR-0012.
- ODR-0011 §7a — notation typing defaults to `xsd:string` + `sh:pattern`;
  this emission keeps notations as plain `xsd:string` Literals.
- ODR-0011 §8a — every scheme carries `opda:ufoCategory` from the
  seven-category UFO framework + `skos:scopeNote @en` with UFO + DOLCE
  source citations (Guizzardi 2005 Ch. 4; Masolo D18 §4.3).

Pipeline:
  1. Build per-scheme metadata tuples (12 named + 4 split / external —
     16 total) declaring `ufo_category`, `steward`, `dct_source`,
     `pref_label`, `title`, `definition`, `scope_note`, `members`.
  2. Build `rdflib.Graph()`; add per-scheme + per-member triples.
  3. Serialise via canonical serialiser; prepend generator-comment header.
  4. Sentinel-pin `dct:modified` to `2026-05-27` so byte-identity CI is
     stable (per the G6 pinning convention established in ADR-0009).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, OWL, RDF, SKOS, XSD

from opda_gen import __version__
from opda_gen.serialiser.canonical import to_canonical_turtle


# --- Namespaces ----------------------------------------------------------
OPDA = Namespace("https://w3id.org/opda/#")
OPDA_V = Namespace("https://w3id.org/opda/vocabularies/")
PROV = Namespace("http://www.w3.org/ns/prov#")


# --- Output ---------------------------------------------------------------
VOCABULARIES_FILENAME = "opda-vocabularies.ttl"


# --- Sentinel-pinned constants per ADR-0010 + G6 convention --------------
# `_VOCABULARIES_LAST_MODIFIED` advances only when a future ADR materially
# mutates the vocabulary content (e.g. ADR-0010 scope expansion to additional
# schemes); CI MUST regenerate with this pinned default so the diff is zero.
_VOCABULARIES_LAST_MODIFIED = "2026-05-27"
# Sentinel for the `# Source commit:` line in the generator-comment header,
# matching the ADR-0009 sentinel convention. Advances when a future ADR
# mutates the emitted vocabulary content.
_VOCABULARIES_SOURCE_COMMIT = "pinned-by-ADR-0010"


# --- Cagle SHACL-AF deprecation-chain rule body (ODR-0011 §5a) ----------
# Per ADR-0010 §"SHACL-AF rule emission (Cagle's deprecation-chain rule)":
# this rule body is held here as a documented constant. It is NOT emitted
# into `opda-vocabularies.ttl` — vocabularies are classes-side, and rule
# emission belongs in `opda-shapes.ttl` under ODR-0004 §3a three-graph
# separation. The current first-batch vocabulary has no deprecated members,
# so the rule has no active targets; ADR-0012 will materialise it into the
# shapes file. The verbatim body is preserved here so the rule's content is
# reviewable from a single point alongside the vocabulary emission it
# guards.
#
# TODO(ADR-0012): emit `opda:DeprecatedConceptValueRule a sh:NodeShape`
# into `opda-shapes.ttl` with the SELECT below as `sh:sparql / sh:select`,
# severity `sh:Info`, message per ODR-0011 §5a Cagle amendment.
_DEPRECATION_CHAIN_RULE_SPARQL = """\
# DeprecationChainRule — non-blocking sh:Info (ODR-0011 §5a, Cagle amendment).
# Targets: opda:EnumValueBearer instances whose chosen value is owl:deprecated.
# Emits: an advisory note listing the deprecated value + (optional) replacement.

PREFIX opda: <https://w3id.org/opda/#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX dct:  <http://purl.org/dc/terms/>

SELECT $this ?value ?successor WHERE {
    $this ?p ?value .
    ?value owl:deprecated true .
    OPTIONAL { ?value dct:isReplacedBy ?successor }
}
"""


# --- Source URI registry --------------------------------------------------
# Per ODR-0004 §7a five-line precedence resolved against ADR-0010 inputs.
# Each scheme cites either its ratifying ODR section (where the ODR ratified
# the UFO category + steward) or the external regulator (where the regulator
# governs the concept per ODR-0011 §4a verbatim-citation discipline).
_ODR_0011_SECTION_8A = URIRef(
    "https://w3id.org/opda/odr/ODR-0011#section-8a-ufo-meta-category"
)
_ODR_0011_SECTION_1A = URIRef(
    "https://w3id.org/opda/odr/ODR-0011#section-1a-scheme-steward"
)
_ODR_0011_SECTION_4A = URIRef(
    "https://w3id.org/opda/odr/ODR-0011#section-4a-regulator-citation"
)
_GOV_UK_COUNCIL_TAX_BANDS = URIRef("https://www.gov.uk/council-tax-bands")
_SAA_COUNCIL_TAX_BANDS = URIRef(
    "https://www.saa.gov.uk/council-tax/council-tax-bands/"
)
_DESNZ_EPC_BANDS = URIRef(
    "https://www.gov.uk/government/publications/"
    "guide-to-energy-performance-certificates-for-the-construction-sale-and-"
    "let-of-dwellings"
)


def _dd_source(leaf_path: str) -> URIRef:
    """Return a per-member `dct:source` IRI pointing at the data-dictionary
    leaf (and, optionally, the enum-member value) that supplied the value.

    The IRI format mirrors the ADR-0010 §"Emission structure" template
    (line 88): `<https://w3id.org/opda/data-dictionary#<leaf_path>>`.
    Bracketed array indices (`[]`) in the leaf path are preserved as in
    the data dictionary so the round-trip back to a leaf record is
    one-to-one; whitespace inside an enum-member suffix is percent-encoded
    to keep the IRI RFC-3986-clean.
    """
    # Percent-encode whitespace inside the fragment so rdflib doesn't warn
    # about invalid URIs; other characters present in the data dictionary
    # (`.`, `[`, `]`, alphanumerics) are tolerated by rdflib's URIRef
    # validator and by Turtle's <iri> grammar.
    safe_path = leaf_path.replace(" ", "%20").replace("'", "%27")
    return URIRef(f"https://w3id.org/opda/data-dictionary#{safe_path}")


# --- Scheme definitions --------------------------------------------------
def _slugify_for_uri(value: str) -> str:
    """Render an enum-notation literal as a URI-safe path segment.

    Rules (deterministic; reversible by inspection):
    - spaces collapse to a single hyphen
    - apostrophes drop (they would otherwise need percent-encoding)
    - other punctuation outside [A-Za-z0-9-_.] is replaced with `-`
    The result is suitable for use as the second-half of an `opda:`
    member URI (`opda:role/Seller-s-Conveyancer` etc.). The raw notation
    value is preserved on the `skos:notation` triple per ODR-0011 §S15.
    """
    out_chars: list[str] = []
    for ch in value:
        if ch.isalnum() or ch in "-_.":
            out_chars.append(ch)
        elif ch == "'":
            # drop; apostrophes in URIs cause more trouble than they save.
            continue
        elif ch == " ":
            out_chars.append("-")
        else:
            out_chars.append("-")
    # Collapse consecutive hyphens to keep the URI readable.
    collapsed: list[str] = []
    prev_hyphen = False
    for ch in out_chars:
        if ch == "-":
            if prev_hyphen:
                continue
            prev_hyphen = True
        else:
            prev_hyphen = False
        collapsed.append(ch)
    return "".join(collapsed).strip("-")


@dataclass(frozen=True)
class Member:
    """A single `skos:Concept` to emit under a scheme.

    `notation` is the canonical machine-readable form (the JSON-enum
    literal value verbatim per ODR-0011 §S15) — stored on the
    `skos:notation` triple unchanged. `pref_label` is the
    human-readable @en label (typically equal to notation for the
    first-batch schemes whose enums are already labels). `definition`
    is the thin definition shown to readers when no glossary entry is
    available. `member_source` is the per-member `dct:source` URI.

    `slug` overrides the URI-segment slug; by default it is derived from
    `notation` via `_slugify_for_uri` (drops apostrophes, collapses
    whitespace to hyphens) so the member URI is RFC-3986-clean.
    """

    notation: str
    pref_label: str
    definition: str
    member_source: URIRef
    slug: str | None = None

    def uri_slug(self) -> str:
        if self.slug is not None:
            return self.slug
        return _slugify_for_uri(self.notation)


@dataclass(frozen=True)
class Scheme:
    """A single `skos:ConceptScheme` to emit.

    `local_name` is the scheme's CamelCase URI segment (e.g. "BuiltFormScheme")
    appended to the `opda:` namespace. `slug_base` is the lowerCamelCase
    base used for per-member URIs (e.g. "builtForm" produces
    `opda:builtForm/Detached`).
    """

    local_name: str
    slug_base: str
    pref_label: str
    title: str
    definition: str
    ufo_category: str
    scope_note: str
    steward: str
    scheme_source: URIRef
    members: tuple[Member, ...]
    # Optional warning emitted as part of the `skos:scopeNote` when the
    # scheme is conceptually well-defined but the data-dictionary enum
    # is missing (ODR-0010 §"Surfaced ambiguity routing", option (a)).
    placeholder_warning: str | None = None

    def scheme_uri(self) -> URIRef:
        return URIRef(f"{OPDA}{self.local_name}")

    def member_uri(self, member: Member) -> URIRef:
        return URIRef(f"{OPDA}{self.slug_base}/{member.uri_slug()}")


# --- Builders for each scheme --------------------------------------------
#
# Mapping from ADR-0010 §"Scheme catalogue" to data-dictionary leaves
# (documented in the ADR-0010 implementation report):
#
#   BuiltFormScheme                  ← propertyPack.buildInformation.building.builtForm
#   CouncilTaxBandSchemeEW           ← propertyPack.councilTax.councilTaxBand (A-H)
#   CouncilTaxBandSchemeScotland     ← split from same leaf (A-I band)
#   CurrentEnergyRatingScheme        ← propertyPack.energyEfficiency.certificate.currentEnergyRating (A-G only)
#   CentralHeatingFuelTypeScheme     ← propertyPack.heating.heatingSystem.centralHeatingDetails.centralHeatingFuel.centralHeatingFuelType
#   HeatingTypeScheme                ← propertyPack.heating.heatingSystem.heatingType
#   OwnershipTypeScheme              ← propertyPack.ownership.ownershipsToBeTransferred[].ownershipType (NTS2 canonical 4-set)
#   TenureKindScheme                 ← propertyPack.marketingTenure (Freehold/Leasehold/Commonhold subset)
#   RoleScheme                       ← participants[].role
#   ParticipantStatusScheme          ← participants[].participantStatus
#   TransactionStatusScheme          ← status (top-level)
#   MilestoneKindScheme              ← external-only (no data-dictionary enum)
#   SellersCapacityScheme            ← participants[].sellersCapacity.capacity
#   AssuranceLevelScheme             ← external-only (eIDAS LoA; placeholder warning)
#   EvidenceMethodScheme             ← external-only (OIDC4IDA; placeholder warning)
#   AddressVariantScheme             ← external-only (ODR-0015 §S015 Q1)


def _builtForm_scheme() -> Scheme:
    leaf = "propertyPack.buildInformation.building.builtForm"
    return Scheme(
        local_name="BuiltFormScheme",
        slug_base="builtForm",
        pref_label="Built Form",
        title="Property built-form classification",
        definition=(
            "Classification of a Property's structural built-form "
            "(detached, semi-detached, terraced, etc.)."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3)."
        ),
        steward="Allemang (property-qualities sub-module steward per S008 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=(
            Member(
                "Detached",
                "Detached",
                "Free-standing dwelling sharing no walls with neighbouring "
                "properties.",
                _dd_source(f"{leaf}.Detached"),
            ),
            Member(
                "Semi-detached",
                "Semi-detached",
                "Dwelling sharing one wall with a single neighbouring property.",
                _dd_source(f"{leaf}.Semi-detached"),
            ),
            Member(
                "Mid-terrace",
                "Mid-terrace",
                "Dwelling within a terrace, sharing walls with neighbouring "
                "properties on both sides.",
                _dd_source(f"{leaf}.Mid-terrace"),
            ),
            Member(
                "End-terrace",
                "End-terrace",
                "Dwelling at the end of a terrace, sharing one wall with a "
                "neighbouring property.",
                _dd_source(f"{leaf}.End-terrace"),
            ),
            Member(
                "Other",
                "Other",
                "Built form falling outside the standard categories; relies "
                "on a free-text note for context.",
                _dd_source(f"{leaf}.Other"),
            ),
        ),
    )


def _council_tax_ew_scheme() -> Scheme:
    return Scheme(
        local_name="CouncilTaxBandSchemeEW",
        slug_base="councilTaxBandEW",
        pref_label="Council Tax Band (England & Wales)",
        title="Council Tax Band — Valuation Office Agency banding (England & Wales)",
        definition=(
            "Valuation Office Agency banding for England & Wales (Bands A–H) "
            "assigned to each domestic property for council tax calculation."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3). Verbatim source: VOA "
            "council-tax bands published at https://www.gov.uk/council-tax-bands."
        ),
        steward="Baker (regulator-cited per ODR-0011 §4a; VOA-governed)",
        scheme_source=_GOV_UK_COUNCIL_TAX_BANDS,
        members=tuple(
            Member(
                band,
                band,
                f"Council tax band {band} as defined by the Valuation Office "
                f"Agency for properties in England & Wales.",
                _GOV_UK_COUNCIL_TAX_BANDS,
            )
            for band in ["A", "B", "C", "D", "E", "F", "G", "H"]
        ),
    )


def _council_tax_scotland_scheme() -> Scheme:
    return Scheme(
        local_name="CouncilTaxBandSchemeScotland",
        slug_base="councilTaxBandScotland",
        pref_label="Council Tax Band (Scotland)",
        title="Council Tax Band — Scottish Assessors Association banding",
        definition=(
            "Scottish Assessors Association banding for Scotland (Bands A–I) "
            "assigned to each domestic property for council tax calculation. "
            "Band I is Scotland-specific."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3). Verbatim source: SAA "
            "council-tax bands published at "
            "https://www.saa.gov.uk/council-tax/council-tax-bands/."
        ),
        steward="Baker (regulator-cited per ODR-0011 §4a; SAA-governed)",
        scheme_source=_SAA_COUNCIL_TAX_BANDS,
        members=tuple(
            Member(
                band,
                band,
                f"Council tax band {band} as defined by the Scottish "
                f"Assessors Association for properties in Scotland.",
                _SAA_COUNCIL_TAX_BANDS,
            )
            for band in ["A", "B", "C", "D", "E", "F", "G", "H", "I"]
        ),
    )


def _current_energy_rating_scheme() -> Scheme:
    return Scheme(
        local_name="CurrentEnergyRatingScheme",
        slug_base="currentEnergyRating",
        pref_label="Current Energy Rating",
        title="Energy Performance Certificate (EPC) current energy rating",
        definition=(
            "EPC current energy rating banding (A–G) published by DESNZ "
            "(Department for Energy Security and Net Zero) for residential "
            "properties in England & Wales."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3). Verbatim source: DESNZ "
            "Energy Performance Certificate guidance."
        ),
        steward="Baker (regulator-cited per ODR-0011 §4a; DESNZ-governed)",
        scheme_source=_DESNZ_EPC_BANDS,
        members=tuple(
            Member(
                band,
                band,
                f"EPC current energy rating band {band} as defined by DESNZ.",
                _DESNZ_EPC_BANDS,
            )
            for band in ["A", "B", "C", "D", "E", "F", "G"]
        ),
    )


def _central_heating_fuel_scheme() -> Scheme:
    leaf = (
        "propertyPack.heating.heatingSystem.centralHeatingDetails."
        "centralHeatingFuel.centralHeatingFuelType"
    )
    members_data = [
        ("Mains gas", "Natural gas supplied via the mains gas network."),
        ("Electricity", "Electrical heating supplied via the mains electricity network."),
        ("Oil", "Heating oil stored on-site for combustion."),
        ("LPG", "Liquefied Petroleum Gas stored on-site for combustion."),
        ("Biomass", "Combustible biological material (e.g. wood pellets)."),
        ("Other", "Fuel type falling outside the standard categories."),
    ]
    return Scheme(
        local_name="CentralHeatingFuelTypeScheme",
        slug_base="centralHeatingFuelType",
        pref_label="Central Heating Fuel Type",
        title="Property central-heating fuel type",
        definition=(
            "Classification of the fuel used by a Property's central heating "
            "system."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3)."
        ),
        steward="Allemang (property-qualities sub-module steward per S008 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _heating_type_scheme() -> Scheme:
    leaf = "propertyPack.heating.heatingSystem.heatingType"
    members_data = [
        (
            "Central heating",
            "Whole-property heating distributed from a single central source.",
        ),
        (
            "Communal heating system",
            "Heating shared between multiple dwellings (e.g. district heating).",
        ),
        (
            "Room heaters only",
            "Heating provided by per-room appliances rather than a central system.",
        ),
        (
            "None",
            "No installed heating system.",
        ),
    ]
    return Scheme(
        local_name="HeatingTypeScheme",
        slug_base="heatingType",
        pref_label="Heating Type",
        title="Property heating-system type",
        definition=(
            "Classification of a Property's overall heating-system "
            "arrangement (central, communal, room-only, or none)."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3)."
        ),
        steward="Allemang (property-qualities sub-module steward per S008 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _ownership_type_scheme() -> Scheme:
    leaf = "propertyPack.ownership.ownershipsToBeTransferred[].ownershipType"
    members_data = [
        ("Freehold", "Outright ownership of the property and the land it sits on."),
        (
            "Leasehold",
            "Ownership of the property for a fixed period under a lease from "
            "the freeholder.",
        ),
        (
            "Commonhold",
            "Freehold ownership of a unit within a commonhold development, "
            "with shared ownership of common parts.",
        ),
        ("Other", "Ownership type falling outside the standard categories."),
    ]
    return Scheme(
        local_name="OwnershipTypeScheme",
        slug_base="ownershipType",
        pref_label="Ownership Type",
        title="Legal-estate ownership type",
        definition=(
            "Classification of a legal estate's ownership structure "
            "(Freehold, Leasehold, Commonhold, Other)."
        ),
        ufo_category="Quale-in-Region",
        scope_note=(
            "UFO: Quale-in-Region (Guizzardi 2005 Ch. 4). DOLCE: "
            "Quality-Region (Masolo D18 §4.3). NTS2 four-value canonical "
            "set used as authority (per data dictionary)."
        ),
        steward="Kendall (LegalEstate steward per S008 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _tenure_kind_scheme() -> Scheme:
    leaf = "propertyPack.marketingTenure"
    members_data = [
        ("Freehold", "Substance Kind: freehold tenure."),
        ("Leasehold", "Substance Kind: leasehold tenure."),
        ("Commonhold", "Substance Kind: commonhold tenure."),
    ]
    return Scheme(
        local_name="TenureKindScheme",
        slug_base="tenureKind",
        pref_label="Tenure Kind",
        title="UFO Substance Kind label for tenure",
        definition=(
            "Substance Kind labels for tenure (Freehold, Leasehold, "
            "Commonhold). Each member binds to its corresponding OWL "
            "sub-class via `skos:exactMatch` per ODR-0011 §8a Substance Kind "
            "label cross-scheme consistency check (NEVER `owl:sameAs`)."
        ),
        ufo_category="Substance Kind label",
        scope_note=(
            "UFO: Substance Kind label (Guizzardi 2005 Ch. 4). Members bind "
            "to OWL sub-classes via `skos:exactMatch`; OPDA pattern per "
            "ODR-0005 Anti-pattern §5."
        ),
        steward="Kendall (LegalEstate steward per S008 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _role_scheme() -> Scheme:
    leaf = "participants[].role"
    members_data = [
        ("Seller", "Party transferring legal title."),
        ("Buyer", "Party acquiring legal title."),
        ("Prospective Buyer", "Party with intent to acquire legal title (pre-offer)."),
        (
            "Seller's Conveyancer",
            "Legal professional acting for the Seller in the transaction.",
        ),
        (
            "Buyer's Conveyancer",
            "Legal professional acting for the Buyer in the transaction.",
        ),
        (
            "Estate Agent",
            "Professional appointed by the Seller to market the property.",
        ),
        (
            "Buyer's Agent",
            "Professional appointed by the Buyer to search for and negotiate "
            "on a property.",
        ),
        (
            "Surveyor",
            "Professional performing a survey or valuation on behalf of a "
            "party to the transaction.",
        ),
        ("Mortgage Broker", "Intermediary arranging mortgage finance for the Buyer."),
        ("Lender", "Institution providing mortgage finance to the Buyer."),
        ("Landlord", "Party granting a tenancy over the property."),
        ("Tenant", "Party occupying the property under a tenancy."),
    ]
    return Scheme(
        local_name="RoleScheme",
        slug_base="role",
        pref_label="Participant Role",
        title="Transaction participant role label",
        definition=(
            "Role labels for the anti-rigid Roles a Person/Organisation "
            "plays as a Participant in a Transaction Relator."
        ),
        ufo_category="Role label",
        scope_note=(
            "UFO: Role label (Guizzardi 2005 Ch. 4 — anti-rigid Roles in a "
            "Relator). DOLCE: Endurant-played-role (Masolo D18 §4)."
        ),
        steward="Guizzardi (RoleMixin steward per S006 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _participant_status_scheme() -> Scheme:
    leaf = "participants[].participantStatus"
    members_data = [
        ("Proposed", "Participant has been proposed but not yet invited."),
        ("Invited", "Participant has been invited to join the transaction."),
        ("Active", "Participant is actively engaged in the transaction."),
        ("Removed", "Participant has been removed from the transaction."),
    ]
    return Scheme(
        local_name="ParticipantStatusScheme",
        slug_base="participantStatus",
        pref_label="Participant Status",
        title="Transaction participant phase label",
        definition=(
            "Phase labels for the lifecycle of a Participant Substance Kind."
        ),
        ufo_category="Phase label",
        scope_note=(
            "UFO: Phase label (Guizzardi 2005 Ch. 4 — intra-Kind phase). "
            "DOLCE: Stage of an Endurant (Masolo D18 §4)."
        ),
        steward="Guizzardi (S006 Q7)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _transaction_status_scheme() -> Scheme:
    leaf = "status"
    # Per ADR-0010 §"Scheme catalogue": Listed, Offered, Accepted, Exchanged,
    # Completed. The data dictionary's actual enum is broader (9 values
    # including 'active', 'For sale', 'Under offer', 'Sold subject to
    # contract', 'Contracts exchanged', 'Completed', 'Cancelled', 'To let',
    # 'Let agreed'). We emit the ADR-named five-phase canonical set; surfaced
    # ambiguity is recorded in the implementation report §Surfaced ambiguity.
    members_data = [
        ("Listed", "Property is listed for sale."),
        ("Offered", "An offer has been made on the property."),
        ("Accepted", "An offer has been accepted, transaction is in progress."),
        ("Exchanged", "Contracts have been exchanged."),
        ("Completed", "Transaction has completed; legal title has transferred."),
    ]
    return Scheme(
        local_name="TransactionStatusScheme",
        slug_base="transactionStatus",
        pref_label="Transaction Status",
        title="Transaction lifecycle phase label",
        definition=(
            "Phase labels for the lifecycle of a Transaction Substance Kind, "
            "tracking the five canonical phases ADR-0010 names (Listed → "
            "Offered → Accepted → Exchanged → Completed)."
        ),
        ufo_category="Phase label",
        scope_note=(
            "UFO: Phase label (Guizzardi 2005 Ch. 4 — intra-Kind phase). "
            "Data dictionary leaf `status` carries a broader 9-value enum "
            "(including marketing-side and let-side phases); the ADR-named "
            "five-phase canonical set is emitted here as the UFO phase set "
            "for the sale lifecycle. Marketing-side / let-side phases "
            "remain available in the data dictionary for downstream "
            "consumers; admission to this scheme requires a Council "
            "amendment (see implementation report §Surfaced ambiguity)."
        ),
        steward="Guizzardi (S007 Q3)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _milestone_kind_scheme() -> Scheme:
    # External-only: no data-dictionary enum lists these milestone codes.
    # The ADR table names them under Method/plan code (Guizzardi).
    # Per ODR-0011 §"Surfaced ambiguity routing" option (a), we emit the
    # scheme with a placeholder warning in scope-note.
    members_data = [
        ("instruction", "Property is instructed by the Seller to be marketed."),
        ("offerAccepted", "An offer is accepted by the Seller."),
        ("exchange", "Contracts are exchanged between Seller and Buyer."),
        ("completion", "Transaction completes; legal title transfers."),
        ("registration", "Title is registered with HM Land Registry."),
    ]
    return Scheme(
        local_name="MilestoneKindScheme",
        slug_base="milestoneKind",
        pref_label="Milestone Kind",
        title="Transaction milestone kind code",
        definition=(
            "Method/plan codes for the procedural milestones authorising "
            "stages of a Transaction Activity (instruction → offerAccepted "
            "→ exchange → completion → registration)."
        ),
        ufo_category="Method/plan code",
        scope_note=(
            "UFO: Method/plan code (Guizzardi 2005 Ch. 4 + Guizzardi & "
            "Wagner 2010 action-modelling). Codes are externally-specified "
            "by the PDTF transaction-lifecycle process; the data dictionary "
            "does not yet carry an enum for these (G-section follow-up "
            "queued to populate)."
        ),
        steward="Guizzardi (S007 Q2)",
        scheme_source=_ODR_0011_SECTION_8A,
        placeholder_warning=(
            "Data-dictionary enum not yet populated; codes are PDTF "
            "process-defined."
        ),
        members=tuple(
            Member(
                notation,
                notation,
                definition,
                URIRef(
                    f"https://w3id.org/opda/pdtf-process#milestone-{notation}"
                ),
            )
            for notation, definition in members_data
        ),
    )


def _sellers_capacity_scheme() -> Scheme:
    leaf = "participants[].sellersCapacity.capacity"
    members_data = [
        ("Legal Owner", "Seller is the legal owner of the property."),
        (
            "Personal Representative for a Deceased Owner",
            "Seller acts as personal representative for a deceased owner.",
        ),
        (
            "Under Power of Attorney",
            "Seller acts under a power of attorney on behalf of the legal "
            "owner.",
        ),
        (
            "Mortgagee in Possession",
            "Seller is a mortgagee that has taken possession of the property.",
        ),
        (
            "Assistant",
            "Seller acts in an assisting capacity (e.g. legal assistant).",
        ),
        ("Other", "Capacity falling outside the standard categories."),
    ]
    return Scheme(
        local_name="SellersCapacityScheme",
        slug_base="sellersCapacity",
        pref_label="Seller's Capacity",
        title="Seller capacity Method/plan code",
        definition=(
            "Method/plan codes for the capacity under which a Seller is "
            "authorised to act in a sale."
        ),
        ufo_category="Method/plan code",
        scope_note=(
            "UFO: Method/plan code (Guizzardi 2005 Ch. 4 + Guizzardi & "
            "Wagner 2010). Codes authorise the Seller's Activity (the act "
            "of selling) under a defined legal arrangement."
        ),
        steward="Guizzardi (S006 Q4)",
        scheme_source=_ODR_0011_SECTION_8A,
        members=tuple(
            Member(notation, notation, definition, _dd_source(f"{leaf}.{notation}"))
            for notation, definition in members_data
        ),
    )


def _assurance_level_scheme() -> Scheme:
    # External-only: eIDAS LoA. Per ODR-0011 §"Surfaced ambiguity routing"
    # option (a): scheme is conceptually well-defined (externally specified),
    # so we emit it with a placeholder-warning scope-note.
    members_data = [
        (
            "Low",
            "Limited degree of confidence in the claimed or asserted identity "
            "of a person (eIDAS LoA Low).",
        ),
        (
            "Substantial",
            "Substantial degree of confidence in the claimed or asserted "
            "identity of a person (eIDAS LoA Substantial).",
        ),
        (
            "High",
            "High degree of confidence in the claimed or asserted identity "
            "of a person (eIDAS LoA High).",
        ),
    ]
    eidas = URIRef("https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32014R0910")
    return Scheme(
        local_name="AssuranceLevelScheme",
        slug_base="assuranceLevel",
        pref_label="Assurance Level",
        title="Identity assurance level (eIDAS)",
        definition=(
            "Quality Values for the eIDAS Levels of Assurance (Low, "
            "Substantial, High) applied to identity-verification claims."
        ),
        ufo_category="Quality Value",
        scope_note=(
            "UFO: Quality Value (Masolo D18 §4.3 — DOLCE Quality Region). "
            "Externally specified by Regulation (EU) No 910/2014 (eIDAS) "
            "Article 8. The data dictionary does not yet carry an enum for "
            "assurance level (G-section follow-up queued)."
        ),
        steward="Moreau (S009 Q3)",
        scheme_source=eidas,
        placeholder_warning=(
            "Data-dictionary enum not yet populated; values inherited "
            "verbatim from eIDAS Article 8."
        ),
        members=tuple(
            Member(notation, notation, definition, eidas)
            for notation, definition in members_data
        ),
    )


def _evidence_method_scheme() -> Scheme:
    # External-only: OIDC4IDA evidence-type vocabulary. Conceptually
    # well-defined externally, so option (a) applies.
    members_data = [
        (
            "Document",
            "Identity evidence obtained by inspecting a physical or digital "
            "identity document (per OIDC4IDA `document` evidence type).",
        ),
        (
            "Electronic-Record",
            "Identity evidence obtained from an electronic record held by an "
            "authoritative source (per OIDC4IDA `electronic_record`).",
        ),
        (
            "Vouch",
            "Identity evidence obtained through attestation by a trusted "
            "third party (per OIDC4IDA `vouch`).",
        ),
    ]
    oidc4ida = URIRef(
        "https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html"
    )
    return Scheme(
        local_name="EvidenceMethodScheme",
        slug_base="evidenceMethod",
        pref_label="Evidence Method",
        title="Identity-evidence method (OIDC4IDA)",
        definition=(
            "Quality Values for the method by which identity evidence was "
            "obtained, per the OIDC4IDA `evidence` taxonomy."
        ),
        ufo_category="Quality Value",
        scope_note=(
            "UFO: Quality Value (Masolo D18 §4.3 — DOLCE Quality Region). "
            "Externally specified by OpenID Connect for Identity Assurance "
            "1.0. The data dictionary does not yet carry an enum for "
            "evidence method (G-section follow-up queued)."
        ),
        steward="Moreau (S009 Q3)",
        scheme_source=oidc4ida,
        placeholder_warning=(
            "Data-dictionary enum not yet populated; values inherited "
            "verbatim from OIDC4IDA."
        ),
        members=tuple(
            Member(notation, notation, definition, oidc4ida)
            for notation, definition in members_data
        ),
    )


def _address_variant_scheme() -> Scheme:
    # External-only: the variant-set is defined by ODR-0015 §S015 Q1
    # (Address Substance Kind + Quality particularising).
    members_data = [
        (
            "marketing",
            "Marketing-presentation variant of the address (estate-agent "
            "format).",
        ),
        (
            "title",
            "HM Land Registry registered-title variant of the address.",
        ),
        (
            "inspire",
            "INSPIRE Directive variant of the address (administrative "
            "boundary alignment).",
        ),
        (
            "postal",
            "Royal Mail PAF-formatted variant of the address.",
        ),
    ]
    odr0015 = URIRef(
        "https://w3id.org/opda/odr/ODR-0015#section-2a-address-variant"
    )
    return Scheme(
        local_name="AddressVariantScheme",
        slug_base="addressVariant",
        pref_label="Address Variant",
        title="Address variant Quality Value",
        definition=(
            "Quality Values for the variant under which an Address is "
            "presented (marketing, title, inspire, postal). Each variant "
            "particularises an underlying Address Substance Kind per "
            "ODR-0015 §2a."
        ),
        ufo_category="Quality Value",
        scope_note=(
            "UFO: Quality Value (Masolo D18 §4.3 — DOLCE Quality Region). "
            "Members particularise an Address Substance Kind per ODR-0015 "
            "§2a. Externally specified by the PDTF address-handling "
            "convention; the data dictionary does not yet carry an enum "
            "for address variant (G-section follow-up queued)."
        ),
        steward="Guizzardi (S015 Q1)",
        scheme_source=odr0015,
        placeholder_warning=(
            "Data-dictionary enum not yet populated; variants defined by "
            "ODR-0015 §S015 Q1."
        ),
        members=tuple(
            Member(notation, notation, definition, odr0015)
            for notation, definition in members_data
        ),
    )


def _all_schemes() -> tuple[Scheme, ...]:
    """Return the 16 schemes in deterministic emission order.

    Emission order follows the ADR-0010 §"Scheme catalogue" row sequence
    so the file is human-readable in the order the ADR lists. Within the
    canonical Turtle output the canonical serialiser then sorts subjects
    by `(type_rank, IRI)`, but the dict-construction order is preserved
    here for documentation purposes.
    """
    return (
        _builtForm_scheme(),
        _council_tax_ew_scheme(),
        _council_tax_scotland_scheme(),
        _current_energy_rating_scheme(),
        _central_heating_fuel_scheme(),
        _heating_type_scheme(),
        _ownership_type_scheme(),
        _tenure_kind_scheme(),
        _role_scheme(),
        _participant_status_scheme(),
        _transaction_status_scheme(),
        _milestone_kind_scheme(),
        _sellers_capacity_scheme(),
        _assurance_level_scheme(),
        _evidence_method_scheme(),
        _address_variant_scheme(),
    )


# --- Graph builder --------------------------------------------------------
def _bind_common(graph: Graph) -> None:
    """Bind the prefixes named in the ADR-0010 §"Emission structure" template.

    The canonical serialiser filters out prefixes whose namespace isn't
    referenced by the graph, so it's safe to bind broadly here.
    """
    graph.bind("opda", OPDA)
    graph.bind("opda-v", OPDA_V)
    graph.bind("skos", SKOS)
    graph.bind("dct", DCTERMS)
    graph.bind("prov", PROV)
    graph.bind("owl", OWL)
    graph.bind("xsd", XSD)


def build_vocabularies_graph() -> Graph:
    """Build the rdflib Graph holding all 16 SKOS Concept Schemes.

    Per ADR-0010 §"Per-scheme metadata MUST-haves":
      - each scheme: rdf:type skos:ConceptScheme + skos:prefLabel @en +
        dct:title @en + skos:definition @en + dct:source + opda:ufoCategory
        + skos:scopeNote @en + opda:hasSteward @en.
    Per ADR-0010 §"Per-member MUST-haves":
      - each member: rdf:type skos:Concept + skos:inScheme + skos:prefLabel
        @en + skos:notation + skos:definition @en + dct:source.
    """
    g = Graph()
    _bind_common(g)

    for scheme in _all_schemes():
        scheme_uri = scheme.scheme_uri()
        g.add((scheme_uri, RDF.type, SKOS.ConceptScheme))
        g.add((scheme_uri, SKOS.prefLabel, Literal(scheme.pref_label, lang="en")))
        g.add((scheme_uri, DCTERMS.title, Literal(scheme.title, lang="en")))
        g.add((scheme_uri, SKOS.definition, Literal(scheme.definition, lang="en")))
        g.add((scheme_uri, DCTERMS.source, scheme.scheme_source))
        g.add((scheme_uri, OPDA.ufoCategory, Literal(scheme.ufo_category)))
        scope_note_text = scheme.scope_note
        if scheme.placeholder_warning:
            scope_note_text = (
                f"{scope_note_text} PLACEHOLDER: {scheme.placeholder_warning}"
            )
        g.add((scheme_uri, SKOS.scopeNote, Literal(scope_note_text, lang="en")))
        g.add((scheme_uri, OPDA.hasSteward, Literal(scheme.steward, lang="en")))

        for member in scheme.members:
            member_uri = scheme.member_uri(member)
            g.add((member_uri, RDF.type, SKOS.Concept))
            g.add((member_uri, SKOS.inScheme, scheme_uri))
            g.add((member_uri, SKOS.prefLabel, Literal(member.pref_label, lang="en")))
            g.add((member_uri, SKOS.notation, Literal(member.notation)))
            g.add((member_uri, SKOS.definition, Literal(member.definition, lang="en")))
            g.add((member_uri, DCTERMS.source, member.member_source))

    return g


# --- Generator-comment header --------------------------------------------
def _comment_header(emission_date: str, git_sha: str) -> str:
    """Build the generator-comment block prepended to `opda-vocabularies.ttl`.

    Mirrors the foundation.py header pattern; per ADR-0010 §"Emission
    structure" lines 55-58 the header cites generator version, source
    commit, and ADR backlinks, plus a DO-NOT-HAND-EDIT warning. Two
    extra explanatory lines reference ODR-0011 §1a + §8a so the human
    reader sees the Council contract this file realises.
    """
    lines = [
        f"# {VOCABULARIES_FILENAME} — OPDA SKOS Concept Schemes",
        f"# Generated by opda-gen {__version__} at {emission_date}; "
        f"DO NOT HAND-EDIT.",
        "# Specification: "
        "https://openpropdata.org.uk/adr/ADR-0007-ontology-generator-specification",
        "# Implementation: "
        "https://openpropdata.org.uk/adr/ADR-0008-generator-implementation-infrastructure",
        "# This emission: "
        "https://openpropdata.org.uk/adr/ADR-0010-skos-vocabulary-emission",
        f"# Generator version: opda-gen-{__version__}",
        f"# Source commit: {git_sha}",
        "# Schemes per ODR-0011 §1a + ODR-0011 §8a seven-category UFO framework.",
        "# Per-scheme deprecation lifecycle per ODR-0011 §5a SHACL-AF pattern",
        "# (rule body deferred to opda-shapes.ttl under ADR-0012).",
        "",
    ]
    return "\n".join(lines) + "\n"


# --- Public API ----------------------------------------------------------
def emit_vocabularies(
    output_dir: Path,
    *,
    emission_date: str | None = None,
    git_sha: str | None = None,
) -> dict[Path, str]:
    """Emit `opda-vocabularies.ttl` into ``output_dir``.

    Returns a dict mapping written ``Path`` → Turtle content (utf-8 str),
    matching the foundation emitter's interface for callers (tests, CI)
    that want to inspect emitted content without re-reading from disk.

    ``emission_date`` and ``git_sha`` default to the pinned constants
    (``_VOCABULARIES_LAST_MODIFIED`` / ``_VOCABULARIES_SOURCE_COMMIT``)
    per ADR-0010. They MUST stay pinned for byte-identity CI to pass;
    the constants advance when a future ADR materially mutates the
    vocabulary content. Override them in tests to exercise alternate
    values.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    date_str = emission_date or _VOCABULARIES_LAST_MODIFIED
    sha_str = git_sha or _VOCABULARIES_SOURCE_COMMIT

    graph = build_vocabularies_graph()
    header = _comment_header(date_str, sha_str)
    body = to_canonical_turtle(graph).decode("utf-8")
    content = header + body

    out_path = output_dir / VOCABULARIES_FILENAME
    out_path.write_text(content, encoding="utf-8", newline="")
    return {out_path: content}


# Backwards-compat alias used by the legacy ADR-0008 CLI stub. The
# `emit-vocabularies` subcommand now dispatches to `emit_vocabularies`;
# the stub `emit` name is kept so anything still importing it sees the
# real implementation instead of the original `NotImplementedError`.
def emit(output_dir: Path) -> dict[Path, str]:  # pragma: no cover - alias
    return emit_vocabularies(output_dir)
