PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX common: <https://w3id.org/opda/candidate/property-pack/0.1/common/>
PREFIX pds: <https://w3id.org/opda/candidate/property-pack/0.1/property-data-services/>
PREFIX conv: <https://w3id.org/opda/candidate/property-pack/0.1/conveyancing/>
ASK { ?subject owl:sameAs ?object }
