#!/usr/bin/env python3
"""Materialise PDTF JSON -> OPDA RDF via an RML mapping (morph-kgc engine).

CLI:
    run_mapping.py --mapping <rml.ttl | morph-config.ini> \
                   --data <instance.json> \
                   --out build/out.nt

morph-kgc is config-driven: an INI names the RML mapping file(s); each mapping's
``rml:source`` names the data file. Two entry modes:

* ``--mapping foo.ini``  -> used as-is (the data source is whatever the referenced
  mapping declares). ``--data`` is ignored in this mode.
* ``--mapping foo.ttl`` -> a temp INI + temp mapping are generated; every
  ``rml:source "..."`` in the mapping is rewritten to point at ``--data`` so the
  same mapping can run against any conformant instance. ``--data`` is required.

Output is N-Triples. Importable via ``main(argv) -> int``.
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

# rml:source "<literal>"  (single- or double-quoted); we swap the literal.
_RML_SOURCE_RE = re.compile(r'(rml:source\s+)(["\'])(?:\\.|(?!\2).)*\2')


def _build_ini_for_ttl(mapping_ttl: Path, data: Path, workdir: Path) -> Path:
    """Rewrite the mapping's rml:source to `data` and emit a morph-kgc INI."""
    text = mapping_ttl.read_text(encoding="utf-8")
    data_abs = str(data.resolve())
    new_text, n = _RML_SOURCE_RE.subn(
        lambda m: f'{m.group(1)}"{data_abs}"', text
    )
    if n == 0:
        # No literal source to rewrite: the mapping references its own data.
        print(
            f"warning: no rml:source string literal found in {mapping_ttl}; "
            f"--data {data} not injected (mapping supplies its own source)",
            file=sys.stderr,
        )
        new_text = text
    temp_ttl = workdir / "mapping.rewritten.ttl"
    temp_ttl.write_text(new_text, encoding="utf-8")

    udfs_path = mapping_ttl.parent / "opda-udfs.py"
    udfs_line = f"udfs={udfs_path.resolve()}\n" if udfs_path.exists() else ""

    ini = workdir / "morph-config.ini"
    ini.write_text(
        "[CONFIGURATION]\n"
        "# generated by run_mapping.py\n"
        f"{udfs_line}"
        "\n"
        "[DataSource1]\n"
        f"mappings={temp_ttl}\n",
        encoding="utf-8",
    )
    return ini


def run(mapping: Path, data: Path | None, out: Path) -> int:
    """Materialise `mapping` (+ `data`) to N-Triples at `out`. Returns 0 on success."""
    if not mapping.exists():
        print(f"error: mapping not found: {mapping}", file=sys.stderr)
        return 2

    # Imported lazily so `--help` and arg errors don't pay the import cost.
    import morph_kgc

    out.parent.mkdir(parents=True, exist_ok=True)

    if mapping.suffix == ".ini":
        config = str(mapping.resolve())
        graph = morph_kgc.materialize(config)
    else:
        if data is None:
            print(
                "error: --data is required when --mapping is an RML .ttl",
                file=sys.stderr,
            )
            return 2
        if not data.exists():
            print(f"error: data not found: {data}", file=sys.stderr)
            return 2
        with tempfile.TemporaryDirectory(prefix="morph-kgc-") as tmp:
            ini = _build_ini_for_ttl(mapping, data, Path(tmp))
            graph = morph_kgc.materialize(str(ini))

    graph.serialize(destination=str(out), format="nt", encoding="utf-8")
    print(f"materialised {len(graph)} triples -> {out}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mapping",
        required=True,
        type=Path,
        help="RML mapping (.ttl) or prepared morph-kgc config (.ini)",
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=None,
        help="PDTF JSON instance (required when --mapping is a .ttl)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("build/out.nt"),
        help="output N-Triples file (default: build/out.nt)",
    )
    args = parser.parse_args(argv)
    return run(args.mapping, args.data, args.out)


if __name__ == "__main__":
    raise SystemExit(main())
